### ISSUE TITLE
El archivo oraculo.c no compila.

### ISSUE THREAD

**Issue by tinomtzlpz** [logralahad/codigotarea#3]
![image](https://user-images.githubusercontent.com/43123591/84329271-e7e92500-ab49-11ea-88c8-98a256f6f534.png)

De acuerdo a la rúbrica para evaluar los ejercicios de programación, la segunda categoría ("¿Compila el programa en Visual C o en gcc?") indica que la misma es indispensable para evaluar el resto de los apartados. Calificación del programa: 15%

**Comment by logralahad** [comment]
Asi es, al momento de recomponer el programa despues de la modificacion para probar con los programas de Jairo, se modificó ese apartado.

**Comment by logralahad** [comment]
Pero bueno, gracias por la atención.
